version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql
      - ./backend/app/sql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3366:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8081:80"
    volumes:
      - ./backend/app/public:/var/www/html
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3366
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./frontend:/app
    tty: true
volumes:
  db_data: