version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    volumes:
      - ./backend/app/public:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./frontend:/app
    tty: true
volumes:
  db_data:
